---
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

  - local: deployment-manifest.yml
  - local: reference.yml
  - local: pointer.yml

stages:
  - start
  - sast
  - secret-detection
  - build
  - approval
  - db-migrator
  - maintenance
  - deploy
  - stop-maintenance
  - test
  - dasts
  - rollback

.sit_rules:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^develop/

variables:
  API_APP_NAME: fhq-api
  API_SOURCE_DIR: fhq-api
  API_DOCKER_IMAGE: $API_APP_NAME:$CURRENT_DOCKER_VERSION
  API_OUTPUT_IMAGE_ARTEFACT: $API_APP_NAME.tar
  API_NEXUS_IQ_APP_ID: CX-CP-FHQ-API
  API_DESIRE_COUNT: 1
  API_SIT_AWS_TASK_DEFINITION_NAME: tskd-cnxcp-sitizapp-fhqapi
  API_SIT_AWS_ECS_SERVICE: 	fhq-sit-api
  API_SIT_AWS_ECS_CLUSTER_NAME: ecs-cp-sitizapp-fhqapi
  API_SIT_AWS_ECR_NAME: sit-fhq-api

  UI_APP_NAME: fhq-ui
  UI_SOURCE_DIR: fhq-ui
  UI_DOCKER_IMAGE: $UI_APP_NAME:$CURRENT_DOCKER_VERSION
  UI_OUTPUT_IMAGE_ARTEFACT: $UI_APP_NAME.tar
  UI_NEXUS_IQ_APP_ID: CX-CP-FHQ-UI
  UI_DESIRE_COUNT: 1
  UI_SIT_AWS_TASK_DEFINITION_NAME: 	tskd-cnxcp-sitizapp-fhqui
  UI_SIT_AWS_ECS_SERVICE: service-sit-fhq-ui
  UI_SIT_AWS_ECS_CLUSTER_NAME: ecs-cp-sitizapp-fhqui
  UI_SIT_AWS_ECR_NAME: sit-fhq-ui

  CX_AGENT_APP_NAME: fhq-cx-agent
  CX_AGENT_SOURCE_DIR: fhq-cx-agent
  CX_AGENT_DOCKER_IMAGE: $CX_AGENT_APP_NAME:$CURRENT_DOCKER_VERSION
  CX_AGENT_OUTPUT_IMAGE_ARTEFACT: $CX_AGENT_APP_NAME.tar
  CX_AGENT_NEXUS_IQ_APP_ID: CX-CP-FHQ-CX-AGENT
  CX_AGENT_DESIRE_COUNT: 1
  CX_AGENT_SIT_AWS_TASK_DEFINITION_NAME: 	tskd-cnxcp-sitizapp-fhqcx-Agent
  CX_AGENT_SIT_AWS_ECS_SERVICE: XX
  CX_AGENT_SIT_AWS_ECS_CLUSTER_NAME: XX
  CX_AGENT_SIT_AWS_ECR_NAME: sit-fhq-cxagent

  GENIE_APP_NAME: fhq-genie
  GENIE_SOURCE_DIR: fhq-genie
  GENIE_DOCKER_IMAGE: $GENIE_APP_NAME:$CURRENT_DOCKER_VERSION
  GENIE_OUTPUT_IMAGE_ARTEFACT: $GENIE_APP_NAME.tar
  GENIE_NEXUS_IQ_APP_ID: CX-CP-FHQ-GENIE
  GENIE_DESIRE_COUNT: 1
  GENIE_SIT_AWS_TASK_DEFINITION_NAME: tskd-cnscp-sitizapp-fhqgenie
  GENIE_SIT_AWS_ECS_SERVICE: XX
  GENIE_SIT_AWS_ECS_CLUSTER_NAME: XX
  GENIE_SIT_AWS_ECR_NAME: sit-fhq-genie

  GENIE_COMPACT_APP_NAME: fhq-genie-cmpt
  GENIE_COMPACT_SOURCE_DIR: fhq-genie-cmpt
  GENIE_COMPACT_DOCKER_IMAGE: $GENIE_COMPACT_APP_NAME:$CURRENT_DOCKER_VERSION
  GENIE_COMPACT_OUTPUT_IMAGE_ARTEFACT: $GENIE_COMPACT_APP_NAME.tar
  GENIE_COMPACT_NEXUS_IQ_APP_ID: CX-CP-FHQ-GENIE-COMPACT
  GENIE_COMPACT_DESIRE_COUNT: 1
  GENIE_COMPACT_SIT_AWS_TASK_DEFINITION_NAME: tskd-cnscp-sitizapp-fhqgenie-cmpt
  GENIE_COMPACT_SIT_AWS_ECS_SERVICE: XX
  GENIE_COMPACT_SIT_AWS_ECS_CLUSTER_NAME: XX
  GENIE_COMPACT_SIT_AWS_ECR_NAME: sit-fhq-genie-compact
