---
include:
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml

  - local: manifest.yml
  - local: reference.yml
  - local: pointer.yml

stages:
  - start
  - sast
  - secret-detection
  - build
  - approval
  - db-migrator
  - maintenance
  - deploy
  - stop-maintenance
  - test
  - dasts
  - rollback

.sit_rules:
  rules:
    - if: $CI_COMMIT_BRANCH =~ /^develop/

variables:
  API_DESIRE_COUNT: 1
  API_SIT_AWS_TASK_DEFINITION_NAME: tskd-cnxcp-sitizapp-fhqapi
  API_SIT_AWS_ECS_SERVICE: 	fhq-sit-api
  API_SIT_AWS_ECS_CLUSTER_NAME: ecs-cp-sitizapp-fhqapi
  API_SIT_AWS_ECR_NAME: sit-fhq-api

  UI_DESIRE_COUNT: 1
  UI_SIT_AWS_TASK_DEFINITION_NAME: 	tskd-cnxcp-sitizapp-fhqui
  UI_SIT_AWS_ECS_SERVICE: service-sit-fhq-ui
  UI_SIT_AWS_ECS_CLUSTER_NAME: ecs-cp-sitizapp-fhqui
  UI_SIT_AWS_ECR_NAME: sit-fhq-ui

  CX_AGENT_DESIRE_COUNT: 1
  CX_AGENT_SIT_AWS_TASK_DEFINITION_NAME: 	tskd-cnxcp-sitizapp-fhqcx-Agent
  CX_AGENT_SIT_AWS_ECS_SERVICE: XX
  CX_AGENT_SIT_AWS_ECS_CLUSTER_NAME: XX
  CX_AGENT_SIT_AWS_ECR_NAME: sit-fhq-cxagent

  GENIE_DESIRE_COUNT: 1
  GENIE_SIT_AWS_TASK_DEFINITION_NAME: tskd-cnscp-sitizapp-fhqgenie
  GENIE_SIT_AWS_ECS_SERVICE: XX
  GENIE_SIT_AWS_ECS_CLUSTER_NAME: XX
  GENIE_SIT_AWS_ECR_NAME: sit-fhq-genie

  GENIE_COMPACT_DESIRE_COUNT: 1
  GENIE_COMPACT_SIT_AWS_TASK_DEFINITION_NAME: tskd-cnscp-sitizapp-fhqgenie-cmpt
  GENIE_COMPACT_SIT_AWS_ECS_SERVICE: XX
  GENIE_COMPACT_SIT_AWS_ECS_CLUSTER_NAME: XX
  GENIE_COMPACT_SIT_AWS_ECR_NAME: sit-fhq-genie-compact
