---
groups:
- name: GoogleCadvisor
  rules:
    - alert: ContainerKilled
      expr: 'time() - container_last_seen > 60'
      for: 0m
      labels:
        severity: warning
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container killed.'
        description: "A container has disappeared and current state value is {{ $value }}."

    - alert: ContainerAbsent
      expr: 'absent(container_last_seen)'
      for: 5m
      labels:
        severity: warning
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container absent.'
        description: "A container is absent for 5 min and current state value is {{ $value }}."

    - alert: ContainerHighCpuUtilization
      expr: '(sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 80'
      for: 2m
      labels:
        severity: warning
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container High CPU utilization.'
        description: "Container CPU utilization is above 80% and current state value is {{ $value }}."

    - alert: ContainerHighMemoryUsage
      expr: '(sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80'
      for: 2m
      labels:
        severity: warning
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container High Memory usage.'
        description: "Container Memory usage is above 80% and current state value is {{ $value }}."

    - alert: ContainerHighThrottleRate
      expr: 'rate(container_cpu_cfs_throttled_seconds_total[3m]) > 1'
      for: 2m
      labels:
        severity: warning
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container high throttle rate'
        description: "Container is being throttled and current state value is {{ $value }}."

    - alert: ContainerLowCpuUtilization
      expr: '(sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) < 20'
      for: 7d
      labels:
        severity: info
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container Low CPU utilization'
        description: "Container CPU utilization is under 20% for 1 week. Consider reducing the allocated CPU and current state value is {{ $value }}."

    - alert: ContainerLowMemoryUsage
      expr: '(sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) < 20'
      for: 7d
      labels:
        severity: info
        app_type: container
        category: cadviser
      annotations:
        summary: '{{ $labels.instance }} server - Container Low Memory usage.'
        description: "Container Memory usage is under 20% for 1 week. Consider reducing the allocated memory and current state value is {{ $value }}."
