---
- name: play for usercreate
  hosts: master
  tasks:
  - name: crete user
    user:
      name: jino
      state: present
  - name: service restart
    service:
      name: sshd
      state: started
  - name: creatre group
    group:
      name: jinoj
      state: present
  - name: create hostname
    hostname: 
      name: jinojo

